# -*- coding: utf-8 -*-
"""Major Project .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQpksmxmSstVzAxkyzFmJTSeFB5LDJZw
"""

#@title { vertical-output: true }

"""
We defined all the values here first, the more we wrote the more we added new variables that needed to be defined,which includes 2 dictionaries, Product_Catalog being predefined
"""
Cart = {}
Product_Catalog = {}
choice = 0
subtotal = 0.0
total_quantity = 0
discount = 0.0
tax = 0.0
total = 0.0
amount_paid = 0.0
change = 0.0
remainder = 0.0
#The first and most important function to be defined
def add_product(item_no, name, cost, stock):
    Product_Catalog[item_no] = {
        "Name": name,
        "Cost": cost,
        "Stock": stock
    }

add_product(1, "Oranges", 50.0, 12)
add_product(2, "Grapes", 200.0, 36)
add_product(3, "Bananas", 25.0, 24)
add_product(4, "Noodles", 40.0, 100)
add_product(5, "Socks", 100.0, 38)
add_product(6, "Tshirt", 500.0, 20)
add_product(7, "Slippers", 250.0, 30)
add_product(8, "WhiteRum", 1500.0, 25)
add_product(9, "Soap", 85.0, 25)
add_product(10, "Soda", 75.0, 30)

"""
we had the low stock check ran before the order is inputed
"""

def check_low_stock():
    for item_no, details in Product_Catalog.items():
        if details["Stock"] < 5:
            print("** LOW STOCK ALERT: ", details["Name"])

print("***Welcome to Best Buy Retail Store***")

def add_to_cart():
    check_low_stock()
    """
    isdigit was added here to prevent letters and numbers above 10 to crash the program
    """
    while True:
        item_no = input("Enter item number: ")
        if not item_no.isdigit() or int(item_no) not in Product_Catalog:
            print("Invalid entry")
            continue

        item_no = int(item_no)

        if Product_Catalog[item_no]["Stock"] == 0:
            print("Sorry, this item is out of stock.")
            break

            """
#thought that would be funny(at this point you must have tried)
"""
        amount = (input("Enter quantity: "))
        if not amount.isdigit() or int(amount) <= 0:
            print ("Nice try, numbers only bud")
            continue
        amount = int(amount)

        if Product_Catalog[item_no]["Stock"] >= amount:
            Cart[item_no] = {
                "Name": Product_Catalog[item_no]["Name"],
                "Cost": Product_Catalog[item_no]["Cost"],
                "Amount": amount
            }
            Product_Catalog[item_no]["Stock"] -= amount
            print(Product_Catalog[item_no]["Name"], "added to cart.")
        else:
            print("Short Supply,")
            print("We only have", Product_Catalog[item_no]["Stock"], "in stock.")
            AddItem = input("Add another item? (1/0): ")
            while AddItem not in ("1", "0"):
              print("Invalid input, please enter 1 or 0.")
              AddItem = input("Add another item? (1/0): ")

            if AddItem == "0":
              return
"""
When testing the code, the remove_from_cart menu did not show up until we added a function call in the order that the functions appear in the code
"""
def remove_from_cart():
    if Cart == {}:
        print("Cart is empty. Nothing to remove.")
        return
    RemoveItem = input("Would you like to remove an item? (1,0): ")
    """
    We were trying to imagine how a regular register button interface would look with ("yes", "no"), but it would be cleaner with ridding the program of any alphabetic capabilities (didnt think about special characters til just now, please dont run any ._.).
    """
    while RemoveItem not in ("1", "0"):
        print("Invalid Selection, please choose (1,0)")
        RemoveItem = input("1/0: ")
    if RemoveItem == "0":
        return

    print("Your Cart:")
    for item_no, details in Cart.items():
        print(f"{item_no}: {details['Name']} - Qty: {details['Amount']}")

    while True:
        try:
            item_no = int(input("Enter the item number to remove: "))
            if item_no in Cart:
                break
            else:
                print("Item not found in cart.")
        except ValueError:
            print("Invalid input. Please enter a number.")

    Product_Catalog[item_no]["Stock"] += Cart[item_no]["Amount"]
    del Cart[item_no]
    print("Item has been removed from the cart.")

def view_cart():
    if not Cart:
        print("Cart is empty.")
        return
    print("--- Shopping Cart ---")
    for item_no, details in Cart.items():
        line_total = details["Cost"] * details["Amount"]
        print(f"{details['Name']}, Qty: {details['Amount']}, Cost: {details['Cost']}, Total: {line_total}")

def checkout():
    global subtotal, total_quantity, discount, tax, total, amount_paid, change, remainder
    if Cart == {}:
        print("Cart is empty. Please add items before checkout.")
        return

    subtotal = 0.0
    total_quantity = 0

    for item_no, details in Cart.items():
        subtotal += details["Cost"] * details["Amount"]
        total_quantity += details["Amount"]

    if total_quantity >= 10:
        discount = subtotal * 0.05
        subtotal = subtotal - discount
        print(f"5% Discount applied: ${discount:.2f}")

    tax = subtotal * 0.10
    total = subtotal + tax

    print(f"Subtotal: {subtotal:.2f}")
    print(f"Tax: {tax:.2f}")
    print(f"Total Due: {total:.2f}")

    while True:
        try:
            amount_paid = float(input("Please enter amount received from customer: "))
            if amount_paid <= 0:
                print("Invalid input, please enter an amount greater than zero.")
                continue
            break
        except ValueError:
            print("Invalid input, please enter numbers only.")

    while amount_paid < total:
        remainder = total - amount_paid
        print(f"Insufficient payment. Still need: {remainder:.2f}")
        extra = float(input("Enter additional amount: "))
        amount_paid += extra

    change = amount_paid - total
    print(f"Your change is: {change:.2f}")
    print("*** Receipt ***")
    print("DS Store")
    print("Where value meets more!")
    print("\n Items Purchased ")
    for item_no, details in Cart.items():
        line_total = details["Cost"] * details["Amount"]
        print(f"{details['Name']}, (Qty: {details['Amount']}) - ${line_total:.2f}")
    print('-' * 20)
    """made string print 20x here instead of typing it out"""

    print("Amount Paid: ", amount_paid)
    print(f"Subtotal: ${subtotal:.2f}")
    print(f"Tax: ${tax:.2f}")
    print(f"Total: ${total:.2f}")
    print("Change: ", change)
    print("Thank you for shopping with us!")

# --- Run the program ---
add_to_cart()
view_cart()
remove_from_cart()
checkout()

